# Generated by Django 4.1.2 on 2023-02-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("singer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Music",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=155)),
                ("genre", models.CharField(max_length=155)),
                ("lyrics", models.TextField(blank=True, null=True)),
                ("audio", models.TextField()),
                ("year", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.TextField()),
                ("is_published", models.BooleanField(default=True)),
                (
                    "singer",
                    models.ManyToManyField(related_name="music", to="singer.singer"),
                ),
            ],
            options={
                "verbose_name": "Music",
                "verbose_name_plural": "Music",
            },
        ),
    ]
