# Generated by Django 4.1.2 on 2023-02-14 22:14

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("signer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Music",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=155)),
                ("ganre", models.CharField(max_length=155)),
                ("lyrics", models.TextField(blank=True, null=True)),
                (
                    "audio",
                    models.FileField(blank=True, upload_to=music.models.upload_audio),
                ),
                ("year", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(blank=True, upload_to=music.models.upload_image),
                ),
                ("is_published", models.BooleanField(default=True)),
                (
                    "signer",
                    models.ManyToManyField(related_name="music", to="signer.signer"),
                ),
            ],
            options={
                "verbose_name": "Music",
                "verbose_name_plural": "Music",
            },
        ),
    ]
