# Generated by Django 4.1.2 on 2023-02-17 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="music",
            old_name="ganre",
            new_name="genre",
        ),
    ]
