# Generated by Django 4.1.2 on 2023-02-21 21:27

from django.db import migrations, models

import music.helpers


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="music",
            name="lyrics",
        ),
        migrations.AlterField(
            model_name="music",
            name="image",
            field=models.ImageField(blank=True, upload_to=music.helpers.upload_image),
        ),
    ]
