# Generated by Django 4.1.2 on 2023-02-21 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("singer", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="singer",
            options={},
        ),
        migrations.RenameField(
            model_name="singer",
            old_name="first_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="singer",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="singer",
            name="description",
        ),
        migrations.RemoveField(
            model_name="singer",
            name="last_name",
        ),
    ]
