# Generated by Django 4.1.2 on 2023-02-20 18:25

import django.db.models.deletion
import phone_field.models
from django.conf import settings
from django.db import migrations, models

import user.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "phone_number",
                    phone_field.models.PhoneField(blank=True, max_length=31, null=True),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to=user.helpers.upload_user_profile__image
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
