# Generated by Django 4.1.2 on 2023-02-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0002_remove_music_lyrics_alter_music_image"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="my_profile",
            field=models.ManyToManyField(to="music.music"),
        ),
    ]
