# Generated by Django 4.1.2 on 2023-02-22 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_profile_my_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="my_profile",
            new_name="my_playlist",
        ),
    ]
