# Generated by Django 4.1.2 on 2023-02-24 12:24

import django.db.models.aggregates
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0002_remove_music_lyrics_alter_music_image"),
        ("user", "0006_alter_profile_my_playlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="my_playlist",
        ),
        migrations.AddField(
            model_name="profile",
            name="my_playlist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.aggregates.Aggregate,
                to="music.music",
            ),
        ),
    ]
