# Generated by Django 4.1.2 on 2023-02-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0002_remove_music_lyrics_alter_music_image"),
        ("user", "0007_remove_profile_my_playlist_profile_my_playlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="my_playlist",
        ),
        migrations.AddField(
            model_name="profile",
            name="my_playlist",
            field=models.ManyToManyField(blank=True, null=True, to="music.music"),
        ),
    ]
